- add ci (#2)
- optimize Dockerfile

diff --git a/docker_setup/Dockerfile b/docker_setup/Dockerfile
--- a/docker_setup/Dockerfile
+++ b/docker_setup/Dockerfile
@@ -1,32 +1,32 @@
-# Dockerfile
-
 # Use a lightweight base image for the Gradle dependencies layer
-FROM openjdk:17-jdk-slim AS gradle_dependencies
+FROM --platform=linux/amd64 openjdk:17-jdk-slim AS builder
 
 # Set the working directory inside the container for the dependencies layer
 WORKDIR /app
 
 # Copy only the necessary Gradle files for dependency resolution
-COPY build.gradle.kts settings.gradle.kts gradlew /app/
-COPY gradle /app/gradle
+COPY build.gradle.kts settings.gradle.kts gradlew gradle /app/
 
-# Resolve and download Gradle dependencies
-RUN ./gradlew dependencies
+# Copy the oapi specification for ./gradlew build
+COPY /src/main/resources/openapi /app/src/main/resources/openapi
 
-# Use a different stage for building the application
-FROM gradle_dependencies AS builder
+# Update access permission before using ./gradlew
+RUN chmod +x ./gradlew
 
-# Set the working directory inside the container for building the application
-WORKDIR /app
+# Resolve and download Gradle dependencies, expect the build to fail, return 0 and allow the docker to continue execution.
+RUN ./gradlew build --no-daemon || return 0
 
-# Copy the entire source code
-COPY src /app/src
+# Copy all files
+COPY . .
+
+# Update access permission after copy all, ./gradlew replaced
+RUN chmod +x ./gradlew
 
 # Build the JAR (Gradle dependencies will be cached from the previous stage)
-RUN ./gradlew build
+RUN ./gradlew build --no-daemon
 
-# Use a valid OpenJDK 17 image for the final application
-FROM openjdk:17-jdk-slim
+# Use a valid JRE 17 image for the final application
+FROM --platform=linux/amd64 eclipse-temurin:17-jre-alpine
 
 # Set the working directory inside the container
 WORKDIR /app
